### ISSUE TITLE
Dependancy issue

### ISSUE THREAD

**Issue by sushruth-06** [AdaptiveBProcess/GenerativeLSTM#1]
There seems to be some issue with the dependency or version of tensorflow 
`tensor_util.py", line 562, in make_tensor_proto
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (3, '100100100100'). Consider casting elements to a supported type.
`
Kindly let me know the right versions of packages that can be used to run the tasks.

**Comment by Mcamargo85** [comment]
Hi, you can find the libraries' version in the lstm_env.yml file. This file also can be used to mount the whole environment, including Keras and Tensorflow, if you are using conda as a manager.
